<?php

/**
 * Created by zhangyh.
 * User: zhangyh
 * Date: 2017/3/13  14:52
 * DESC
 */
namespace App\S\Wheel;

use App\Lib\Redis\ActivityWheelLogRedis;
use App\Lib\Redis\ActivityWheelRedis;
use App\Lib\Redis\ActivityWheelWinRedis;
use App\S\Member\MemberService;
use App\S\S;

class ActivityWheelWinService extends S
{
    /**
     *
     * FileSystemService constructor.
     * @desc 构造方法
     */
    public function __construct()
    {
        $this->request = app('request');
        parent::__construct('ActivityWheelWin');
    }

    /**
     * @author zhangyh
     * @Email zhangyh_private@foxmail.com
     * @date 20170626
     * @desc 根据id获取列表
     * @param $id
     * @return array
     */
    public function getRowById($id)
    {
        $result = [];
        $redis = new ActivityWheelWinRedis();
        $result = $redis->getRow($id);

        if (empty($result)) {
            $result = $this->model->wheres(['id' => $id])->first();
            if (!$result) {
                return [];
            }
            $result = $result->toArray();
            $redis->addArr($result);
        }
        return $result;
    }

    public function getListById(array $idArr)
    {
        $result = [];
        $redisData = $mysqlData = [];
        $redisId = [];
        $idArr = array_values($idArr);
        $redis = new ActivityWheelWinRedis();
        $result = $redis->getArr($idArr);
        foreach ($idArr as $key => $value) {
            if (empty($result[$key]))
                $redisId[] = $value;
            else
                $redisData[$value] = $result[$key];
        }
        if (!empty($redisId)) {
            $mysqlData = $this->model->whereIn('id',$redisId)->get()->toArray();
            $mysqlData = array_column($mysqlData, null,'id');
            $redis->setArr($mysqlData);
        }
        return sortArr($idArr, ($redisData + $mysqlData) );
    }

    /**
     * @author zhangyh
     * @Email zhangyh_private@foxmail.com
     * @date 20170626
     * @desc 根据id更新数据
     * @param $id
     * @param $data
     */
    public function update($id,$data){
        $res = $this->model->where('id',$id)->update($data);
        if ($res){
            $storeRedis = new ActivityWheelWinRedis();
            return $storeRedis->update($id,$data);
        }
    }

    public function del($id)
    {
        $res = $this->model->where('id',$id)->delete();
        if ($res){
            $storeRedis = new ActivityWheelWinRedis();
            return $storeRedis->del($id);
        }else{
            return false;
        }
    }

    public function add($data)
    {
        return $this->model->insertGetId($data);
    }

    public function getlistPage($where,$orderBy = 'id', $order = 'desc')
    {
        return $this->getListWithPage($where, $orderBy, $order);
    }



    /**
     * @author zhangyh
     * @Email zhangyh_private@foxmail.com
     * @date 20170720
     * @desc 批量更新
     */
    public function batchUpdate($ids,$data)
    {
        $res = $this->model->whereIn('id',$ids)->update($data);
        if ($res){
            $redis = new ActivityWheelWinRedis();
            $redisUpData = [];
            foreach ($ids as $val){
                $redisUpData[] = array_merge($data,['id'=>$val]);
            }
            return $redis->updateArr($redisUpData);
        }else{
            return false;
        }
    }


    /**
     * @author zhangyh
     * @Email zhangyh_private@foxmail.com
     * @date 20170801
     * @desc 根绝wheelid 获取记录
     * @param $id
     */
    public function getByWheelId($id)
    {
        $where = ['wheel_id'=>$id];

        if ($this->request->input('status')){
            if ($this->request->input('status') == 1){
                $where['is_win'] = 0;
            }else{
                $where['is_win'] = 1;
            }
        }

        $logData = $this->getListWithPage($where);

        $mids = [];
        foreach ($logData[0]['data'] as $val){
            $mids[] = $val['mid'];
        }
        $res= (new MemberService())->getListById($mids);
        $memberData = [];
        foreach ($res as $val){
            $memberData[$val['id']]['nickname'] = $val['nickname'];
            $memberData[$val['id']]['headimgurl'] = $val['headimgurl'];
            $memberData[$val['id']]['id'] = $val['id'];
        }
        foreach ($logData[0]['data'] as &$value){
            $value['member'] = $memberData[$value['mid']];
        }
        return $logData;
    }


    /**
     * @author zhangyh
     * @Email zhangyh_private@foxmail.com
     * @date 20170802
     * @desc获取统计数据
     * @param array $where
     * @return mixed
     */
    public function count($where = [])
    {
        return parent::count($where); // TODO: Change the autogenerated stub
    }


}























