<?php

/**
 * Created by zhangyh.
 * User: zhangyh
 * Date: 2017/3/13  14:52
 * DESC
 */

namespace App\S\Wheel;

use App\Lib\Redis\ActivityWheelLogRedis;
use App\Lib\Redis\ActivityWheelRedis;
use App\Lib\Redis\ActivityWheelTimeRedis;
use App\S\Member\MemberService;
use App\S\S;

class ActivityWheelTimeService extends S
{
    /**
     *
     * FileSystemService constructor.
     * @desc 构造方法
     */
    public function __construct()
    {
        $this->request = app('request');
        parent::__construct('ActivityWheelTime');
    }

    /**
     * @author zhangyh
     * @Email zhangyh_private@foxmail.com
     * @date 20170626
     * @desc 根据id获取列表
     * @param $id
     * @return array
     */
    public function getRowById($id)
    {
        $result = [];
        $redis = new ActivityWheelTimeRedis();
        $result = $redis->getRow($id);

        if (empty($result)) {
            $result = $this->model->wheres(['id' => $id])->first();
            if (!$result) {
                return [];
            }
            $result = $result->toArray();
            $redis->addArr($result);
        }
        return $result;
    }

    public function getListById(array $idArr)
    {
        $result = [];
        $redisData = $mysqlData = [];
        $redisId = [];
        $idArr = array_values($idArr);
        $redis = new ActivityWheelTimeRedis();
        $result = $redis->getArr($idArr);
        foreach ($idArr as $key => $value) {
            if (empty($result[$key]))
                $redisId[] = $value;
            else
                $redisData[$value] = $result[$key];
        }
        if (!empty($redisId)) {
            $mysqlData = $this->model->whereIn('id', $redisId)->get()->toArray();
            $mysqlData = array_column($mysqlData, null, 'id');
            $redis->setArr($mysqlData);
        }
        return sortArr($idArr, ($redisData + $mysqlData));
    }

    /**
     * @author zhangyh
     * @Email zhangyh_private@foxmail.com
     * @date 20170626
     * @desc 根据id更新数据
     * @param $id
     * @param $data
     */
    public function update($id, $data)
    {
        $res = $this->model->where('id', $id)->update($data);
        if ($res) {
            $storeRedis = new ActivityWheelTimeRedis();
            return $storeRedis->update($id, $data);
        }
    }

    public function del($id)
    {
        $res = $this->model->where('id', $id)->delete();
        if ($res) {
            $storeRedis = new ActivityWheelTimeRedis();
            return $storeRedis->del($id);
        } else {
            return false;
        }
    }

    public function add($data)
    {
        return $this->model->insertGetId($data);
    }

    public function getlistPage($where, $orderBy = '', $order = '')
    {
        return $this->getListWithPage($where, $orderBy, $order);
    }


    /**
     * @author zhangyh
     * @Email zhangyh_private@foxmail.com
     * @date 20170720
     * @desc 批量更新
     * @update 何书哲 2019年07月17日 修改redis批量更新
     */
    public function batchUpdate($ids, $data)
    {
        $res = $this->model->whereIn('id', $ids)->update($data);
        if ($res) {
            $redis = new ActivityWheelTimeRedis();
            // update 何书哲 2019年07月17日 修改redis批量更新
            $redisUpData = [];
            foreach ($ids as $val) {
                $redisUpData[] = array_merge($data, ['id' => $val]);
            }
            return $redis->updateArr($redisUpData);
        } else {
            return false;
        }
    }


    /**
     * @author zhangyh
     * @Email zhangyh_private@foxmail.com
     * @date 20170802
     * @desc获取统计数据
     * @param array $where
     * @return mixed
     */
    public function count($where = [])
    {
        return parent::count($where); // TODO: Change the autogenerated stub
    }

    public function getList($where = [], $skip = "", $perPage = "", $orderBy = "", $order = "")
    {
        return parent::getList($where, $skip, $perPage, $orderBy, $order); // TODO: Change the autogenerated stub
    }

    /**
     * @author zhangyh
     * @Email zhangyh_private@foxmail.com
     * @date 20170807
     * @desc 递增
     * @param $id
     * @param $num
     * @return bool
     */
    public function increment($id, $field, $num)
    {
        $where = [
            'id' => $id,
        ];

        $res = $this->model->wheres($where)->increment($field, $num);
        if ($res) {
            $redis = new ActivityWheelTimeRedis();
            $redis->incr($id, $field, $num);
            return true;
        } else {
            return false;
        }
    }


}























