<?php

/**
 * Created by zhangyh.
 * User: zhangyh
 * Date: 2017/3/13  14:52
 * DESC
 */
namespace App\S\Distribute;
use App\Lib\Redis\DistributeApplayLogRedis;
use App\Lib\Redis\DistributeApplayPageRedis;
use App\S\S;

class DistributeGradeService extends S
{
    /**
     *
     * FileSystemService constructor.
     * @desc 构造方法
     */
    public function __construct()
    {
        parent::__construct('DistributeGrade');
    }



    public function add($data){
        return $this->model->insertGetId($data);
    }


    public function updata($id,$data)
    {
        return $this->model->where('id',$id)->update($data);
    }


    public function del($id)
    {

        $this->model->where('id',$id)->delete();
    }


    public function getByWhere($where=[],$order='id',$orderBy='asc')
    {
        $query = $this->model;
        if ($where){
            $query = $query->wheres($where);
        }
        $result = $query->orderBy($order,$orderBy)->get()->toArray();
        return $result;
    }


    /**
     * 是否存在
     * @param $where
     * @author 张永辉 2018年12月06
     */
    public function isExistByWhere($where)
    {
        return !!$this->model->wheres($where)->get(['id'])->toArray();
    }


    public function count($where = [])
    {
        return parent::count($where); // TODO: Change the autogenerated stub
    }


}























