<?php

namespace App\S\AliApp;
use App\Lib\Redis\AliappConfigRedis;
use App\S\S;

/**
 * Created by zhangyh.
 * User: zhangyh
 * Date: 2018/7/23
 * Time: 11:34
 */
class AliappConfigService extends S
{


    /**
     *
     * FileSystemService constructor.
     * @desc 构造方法
     */
    public function __construct()
    {
        parent::__construct('AliappConfig');
    }


    /**
     * 根据id获取配置信息
     * @param $id
     * @return array
     * @author 张永辉 2018年7月23
     */
    public function getRowById($id)
    {
        $result = [];
        $redis = new AliappConfigRedis();
        $result = $redis->getRow($id);

        if (empty($result)) {
            $result = $this->model->wheres(['id' => $id])->first();
            if (!$result) {
                return [];
            }
            $result = $result->toArray();
            $redis->addArr($result);
        }
        return $result;
    }

    public function getListById(array $idArr)
    {
        $result = [];
        $redisData = $mysqlData = [];
        $redisId = [];
        $idArr = array_values($idArr);
        $redis = new AliappConfigRedis();
        $result = $redis->getArr($idArr);
        foreach ($idArr as $key => $value) {
            if (empty($result[$key]))
                $redisId[] = $value;
            else
                $redisData[$value] = $result[$key];
        }
        if (!empty($redisId)) {
            $mysqlData = $this->model->whereIn('id',$redisId)->get()->toArray();
            $mysqlData = array_column($mysqlData, null,'id');
            $redis->setArr($mysqlData);
        }
        return sortArr($idArr, ($redisData + $mysqlData) );
    }

    /**
     * 根绝id更新配置信息
     * @param $id
     * @param $data
     * @return mixed
     * @author 张永辉 2018年7月23日
     */
    public function update($id,$data){
        $res = $this->model->where('id',$id)->update($data);
        if ($res){
            $storeRedis = new AliappConfigRedis();
            return $storeRedis->update($id,$data);
        }
    }

    public function del($id)
    {
        $res = $this->model->where('id',$id)->delete();
        if ($res){
            $storeRedis = new AliappConfigRedis();
            return $storeRedis->del($id);
        }else{
            return false;
        }
    }

    public function add($data)
    {
        return $this->model->insertGetId($data);
    }

    public function getlistPage($where=[])
    {
        return $this->getListWithPage($where, '', '');
    }

    public function getList($where = [], $skip = "", $perPage = "", $orderBy = "", $order = "")
    {
        return parent::getList($where, $skip, $perPage, $orderBy, $order); // TODO: Change the autogenerated stub
    }


    /**
     *
     * @param $appid
     * @author 张永辉
     */
    public function getRowByAppId($appid)
    {
        $configData = $this->model->where('auth_app_id',$appid)->first();
        if (!$configData){
            return [];
        }else{
            return $configData->toArray();
        }
    }

    /***
     * todo 查询支付宝小程序配置信息
     * @param array $where
     * @param string $orderBy
     * @param string $order
     * @param int $pageSize
     * @return array
     * @author 张国军 2018年07月31日
     */
    public function getListWithPage($where = [], $orderBy = '', $order = '',$pageSize=15)
    {
        return parent::getListWithPage($where,$orderBy,$order,$pageSize);
    }

}