<?php
namespace App\S\Staff;
use App\S\S;

class StaffOperLogService extends S{

	/**
     *
     * FileSystemService constructor.
     * @desc 构造方法
     */
    public function __construct()
    {
        parent::__construct('StaffOperLog');
    }

    /**
     * @auth zhangyh
     * @Email zhangyh_private@foxmail.com
     * @date 201703161055
     * @desc 写日志
     * @param string $content
     */
    public function write($content='',$type = 0, $xcxConfigId = 0)
    {
        $userData = session('userData');
        $staffOperLogData = [
            'oper_id'       => isset($userData['id']) ? $userData['id'] : 0,
            'login_name'    => isset($userData['login_name']) ? $userData['login_name'] : '',
            'name'          => isset($userData['name']) ? $userData['name'] : '',
            'content'       => $content,
            'type'          => $type,
            'xcx_config_id' => $xcxConfigId
        ];
        return $this->model->insertGetId($staffOperLogData);
    }

    /**
     * 根据条件获取最新的一条客服日志数据
     * author: meijie
     * @param array $where
     * @return mixed
     */
    public function readCusInfo($where = [])
    {
        return $this->model->where($where)->orderBy('created_at','desc')->first();
    }
    
    public function getList($where = [], $skip = "", $perPage = "", $orderBy = "", $order = "")
    {
        return parent::getList($where, $skip, $perPage, $orderBy, $order); // TODO: Change the autogenerated stub
    }

    /**
     * 根据主键id数组获取列表
     * @param array $idArr
     * @return mixed
     */
    public function getListById(array $idArr)
    {
        $idArr = array_values($idArr);
        $mysqlData = $this->model->whereIn('id',$idArr)->get()->toArray();
        $mysqlData = array_column($mysqlData, null,'id');
        return sortArr($idArr,  $mysqlData);
    }

    public function getListWithPage($where = [], $orderBy = '', $order = '', $pageSize = 0)
    {
        return parent::getListWithPage($where, $orderBy, $order, $pageSize); // TODO: Change the autogenerated stub
    }

}

