<?php
/**
 * Created by PhpStorm.
 * User: hsz
 * Date: 2018/5/15
 * Time: 15:13
 */

namespace App\S\Scratch;

use App\Lib\Redis\ActivityScratchLogRedis;
use App\Lib\Redis\ActivityScratchRedis;
use App\Lib\Redis\ActivityScratchWinRedis;
use App\S\Member\MemberService;
use App\S\S;

class ActivityScratchWinService extends S
{
    /**
     *
     * FileSystemService constructor.
     * @desc 构造方法
     */
    public function __construct()
    {
        $this->request = app('request');
        parent::__construct('ActivityScratchWin');
    }

    /**
     * @author hsz
     * @desc 根据id获取列表
     * @param $id
     * @return array
     */
    public function getRowById($id)
    {
        $result = [];
        $redis = new ActivityScratchWinRedis();
        $result = $redis->getRow($id);
        if (empty($result)) {
            $result = $this->model->wheres(['id' => $id])->first();
            if (!$result) {
                return [];
            }
            $result = $result->toArray();
            $redis->addArr($result);
        }
        return $result;
    }

    public function getListById(array $idArr)
    {
        $result = [];
        $redisData = $mysqlData = [];
        $redisId = [];
        $idArr = array_values($idArr);
        $redis = new ActivityScratchWinRedis();
        $result = $redis->getArr($idArr);
        foreach ($idArr as $key => $value) {
            if (empty($result[$key]))
                $redisId[] = $value;
            else
                $redisData[$value] = $result[$key];
        }
        if (!empty($redisId)) {
            $mysqlData = $this->model->whereIn('id', $redisId)->get()->toArray();
            $mysqlData = array_column($mysqlData, null, 'id');
            $redis->setArr($mysqlData);
        }
        return sortArr($idArr, ($redisData + $mysqlData));
    }

    /**
     * @author hsz
     * @desc 根据id更新数据
     * @param $id
     * @param $data
     */
    public function update($id, $data)
    {
        $res = $this->model->where('id', $id)->update($data);
        if ($res) {
            $storeRedis = new ActivityScratchWinRedis();
            return $storeRedis->update($id, $data);
        }
    }

    public function del($id)
    {
        $res = $this->model->where('id', $id)->delete();
        if ($res) {
            $storeRedis = new ActivityScratchWinRedis();
            return $storeRedis->del($id);
        } else {
            return false;
        }
    }

    public function add($data)
    {
        return $this->model->insertGetId($data);
    }

    public function getlistPage($where, $orderBy = 'id', $order = 'desc')
    {
        return $this->getListWithPage($where, $orderBy, $order);
    }

    /**
     * 批量更新
     * @author 何书哲 2017年07月20日
     * @update 何书哲 2019年07月17日 修改redis批量更新
     */
    public function batchUpdate($ids, $data)
    {
        $res = $this->model->whereIn('id', $ids)->update($data);
        if ($res) {
            $redis = new ActivityScratchWinRedis();
            // update 何书哲 2019年07月17日 修改redis批量更新
            $redisUpData = [];
            foreach ($ids as $val) {
                $redisUpData[] = array_merge($data, ['id' => $val]);
            }
            return $redis->updateArr($redisUpData);
        } else {
            return false;
        }
    }

    /**
     * @author hsz
     * @desc获取统计数据
     * @param array $where
     * @return mixed
     */
    public function count($where = [])
    {
        return parent::count($where); // TODO: Change the autogenerated stub
    }


}