<?php
/**
 * Created by PhpStorm.
 * User: meijie
 * Date: 2017/8/30
 * Time: 14:57
 */

namespace App\S\Wechat;


use App\S\S;


class WeChatShopConfService extends S
{
    public function __construct()
    {
        parent::__construct('WeixinConfigSub');
    }

    //店铺授权绑定添加时操作
    public function createData($data)
    {
        return $this->model->insertGetId($data);
    }

    public function updateData($data)
    {
        $input = [
            'payee' => $data['config']['payee'],
            'app_secret' => $data['config']['app_secret'],
            'mch_key' => $data['config']['mch_key'],
            'mch_id' => $data['config']['mch_id'],
            'status' => $data['status'],
            'app_id' => $data['config']['app_id'],
        ];
        $dbResult = $this->model->where(['id' => $data['id']])->update($input);
        return $dbResult;
    }

    public function update($id, $data)
    {

        return $this->model->where(['id' => $id])->update($data);
    }

    public function delData($where = [])
    {
        return $this->model->where($where)->delete();
    }

    public function getRowByWid($wid)
    {
        $where['wid'] = $wid;
        $data = $this->model->where($where)->order('created_at', 'desc')->first();
        if (!empty($data)) {
            $data = $data->toArray();
        }
        return $data;
    }

    public function getConfigByWid($wid)
    {
        $data = $this->model->select(['payee', 'app_id', 'original_id', 'app_secret', 'mch_id', 'mch_key', 'service_type_info', 'verify_type_info'])->where(['wid' => $wid])->orderBy('created_at', 'desc')->first();
        if (!empty($data)) {
            $data = $data->toArray();
        }
        return $data;
    }

    public function getPayConfigByWid($wid)
    {
        $field = ['payee', 'app_id', 'app_secret', 'mch_id', 'mch_key', 'status'];
        $data = $this->model->select($field)->where(['wid' => $wid])->first();
        if (!empty($data)) {
            $data = $data->toArray();
            foreach ($field as $value) {
                if (empty($data[$value])) {
                    return false;
                }
            }
        }
        return $data;
    }

    public function getList($where = [], $skip = "", $perPage = "", $orderBy = "", $order = "")
    {
        return parent::getList($where, $skip, $perPage, $orderBy, $order); // TODO: Change the autogenerated stub
    }

    public function getListById(array $idArr)
    {
        $mysqlData = $this->model->whereIn('id', $idArr)->get()->toArray();
        $mysqlData = array_column($mysqlData, null, 'id');
        return sortArr($idArr, $mysqlData);
    }

    /**
     * 根据appid获取授权信息
     * @param  [string] $appid [微信公众号appid]
     * @return [type]        [description]
     * add by wuxiaoping 2018.05.02
     * @update 何书哲 2019年07月01日 app_id对应记录不存在时toArray()报错修改
     */
    public function getConfigByAppid($appid)
    {
        //update 何书哲 2019年07月01日 app_id对应记录不存在时toArray()报错修改
        $row = $this->model->where(['app_id' => $appid])->first();
        if ($row) {
            return $row->toArray();
        }
        return [];
    }


}