<?php

namespace App\Lib\Redis;


class ActivityScratchRedis extends RedisInterface
{
    protected $prefixKey = 'activity_scratch';
    protected $timeOut   = 86400;
    public function __construct($key = "")
    {
        parent::__construct($key);
    }

    public function getRow($id)
    {
        return $this->redis->HGETALL($this->key . $id);
    }

    public function update($id,$data)
    {
        $id = trim($id);
        if ($this->redis->exists($this->key.$id)){
            return $this->redis->hmset($this->key.$id,$data);
        }
        return true;
    }

    public function del($id)
    {
        if ($this->redis->exists($this->key.$id)){
            return $this->redis->del($this->key.$id);
        }
        return true;
    }

    public function incr($id, $field, $num)
    {
        parent::incr($id, $field, $num); // TODO: Change the autogenerated stub
    }
}