<?php
/**
 * Created by PhpStorm.
 * Author: MeiJay
 * Date: 2018/1/26
 * Time: 15:20
 */

namespace App\S\Message;


use App\S\S;

class MessageTemplateLogService extends S
{
    public function __construct()
    {
        parent::__construct('MessageTemplateLog');
    }

    public function getAllList($wid,$data=[],$orderBy='')
    {
        $where['wid'] = $wid;
        $order = $orderBy ?? 'created_at';
        return $this->getListWithPage($where,$order,'DESC');
    }

    //添加数据
    public function add($data)
    {
        return $this->model->insertGetId($data);
    }

    public function delete($id)
    {
        return $this->model->where(['id' => $id])->delete();
    }

    public function getRowById($id)
    {
        $data = $this->model->find($id);
        if ($data) {
            $data = $data->toArray();
        }
        return $data;
    }

    public function count($where = [])
    {
        return parent::count($where); // TODO: Change the autogenerated stub
    }

    public function increase($where = [])
    {
        return $this->model->where($where)->increment('send_count');
    }

    public function getListWithPage($where = [], $orderBy = '', $order = '', $pageSize = 0)
    {
        return parent::getListWithPage($where, $orderBy, $order, $pageSize); // TODO: Change the autogenerated stub
    }

    public function getListById($idArr = [])
    {
        //以hash类型保存到redis中
        $mysqlData = $this->model->whereIn('id',$idArr)->get()->toArray();
        $mysqlData = array_column($mysqlData, null,'id');
        return sortArr($idArr,  $mysqlData);
    }





}